# Generated by Django 5.2.5 on 2025-08-22 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_rating_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='recipe',
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
